// :arch: Provider registry — static definitions for all supported LLM providers
// :deps: consumed by catalog worker, CatalogSync, and router config
// :rules: id must match default-catalog.json provider ids; adapter determines API compatibility layer
export const PROVIDERS = [
  {
    id: "google",
    name: "Google",
    adapter: "google",
    base_url: "https://generativelanguage.googleapis.com/v1beta/openai",
    trust_tier: "standard",
    docs_url: "https://ai.google.dev/docs",
  },
  {
    id: "groq",
    name: "Groq",
    adapter: "openai",
    base_url: "https://api.groq.com/openai/v1",
    trust_tier: "standard",
    docs_url: "https://console.groq.com/docs",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    adapter: "openai",
    base_url: "https://api.cerebras.ai/v1",
    trust_tier: "open",
    docs_url: "https://inference-docs.cerebras.ai",
  },
  {
    id: "sambanova",
    name: "SambaNova",
    adapter: "openai",
    base_url: "https://api.sambanova.ai/v1",
    trust_tier: "open",
    docs_url: "https://community.sambanova.ai/docs",
  },
  {
    id: "mistral",
    name: "Mistral",
    adapter: "openai",
    base_url: "https://api.mistral.ai/v1",
    trust_tier: "open",
    docs_url: "https://docs.mistral.ai",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    adapter: "openai",
    base_url: "https://openrouter.ai/api/v1",
    trust_tier: "standard",
    docs_url: "https://openrouter.ai/docs",
  },
  {
    id: "cohere",
    name: "Cohere",
    adapter: "cohere",
    base_url: "https://api.cohere.com/v2",
    trust_tier: "standard",
    docs_url: "https://docs.cohere.com",
  },
  {
    id: "ollama",
    name: "Ollama (Local)",
    adapter: "openai",
    base_url: "http://localhost:11434/v1",
    trust_tier: "open",
    docs_url: "https://ollama.com",
    is_local: true,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    adapter: "openai",
    base_url: "https://api.deepseek.com/v1",
    trust_tier: "standard",
    docs_url: "https://platform.deepseek.com/docs",
  },
  {
    id: "alibaba",
    name: "Alibaba Cloud",
    adapter: "openai",
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    trust_tier: "standard",
    docs_url: "https://www.alibabacloud.com/help/model-studio",
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    adapter: "openai",
    base_url: "https://api.fireworks.ai/inference/v1",
    trust_tier: "standard",
    docs_url: "https://docs.fireworks.ai",
  },
  {
    id: "together",
    name: "Together AI",
    adapter: "openai",
    base_url: "https://api.together.xyz/v1",
    trust_tier: "standard",
    docs_url: "https://docs.together.ai",
  },
  {
    id: "inception",
    name: "Inception Labs",
    adapter: "openai",
    base_url: "https://api.inceptionlabs.ai/v1",
    trust_tier: "standard",
    docs_url: "https://docs.inceptionlabs.ai",
  },
  {
    id: "xai",
    name: "xAI",
    adapter: "openai",
    base_url: "https://api.x.ai/v1",
    trust_tier: "standard",
    docs_url: "https://docs.x.ai",
  },
  {
    id: "openai",
    name: "OpenAI",
    adapter: "openai",
    base_url: "https://api.openai.com/v1",
    trust_tier: "standard",
    docs_url: "https://platform.openai.com/docs",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    adapter: "anthropic",
    base_url: "https://api.anthropic.com/v1",
    trust_tier: "standard",
    docs_url: "https://docs.anthropic.com",
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    adapter: "openai",
    base_url: "https://integrate.api.nvidia.com/v1",
    trust_tier: "standard",
    docs_url: "https://build.nvidia.com/docs",
  },
  {
    id: "github",
    name: "GitHub Models",
    adapter: "openai",
    base_url: "https://models.inference.ai.azure.com",
    trust_tier: "standard",
    docs_url: "https://docs.github.com/en/github-models",
  },
  {
    id: "cloudflare",
    name: "Cloudflare Workers AI",
    adapter: "openai",
    base_url: "https://api.cloudflare.com/client/v4/accounts/{id}/ai/v1",
    trust_tier: "standard",
    docs_url: "https://developers.cloudflare.com/workers-ai",
  },
  {
    id: "huggingface",
    name: "HuggingFace",
    adapter: "openai",
    base_url: "https://api-inference.huggingface.co/v1",
    trust_tier: "standard",
    docs_url: "https://huggingface.co/docs/api-inference",
  },
];
export const PROVIDER_MAP = Object.fromEntries(PROVIDERS.map((p) => [p.id, p]));
